/* eslint-disable */
/**
 * AUTO-GENERATED by shared/scripts/gen-map-catalog.mjs — do not edit.
 * Source folder: shared/src/maps/*.json
 *
 * - ranked-classic (2p) ← ranked-classic.json
 * - solo-classic (1p) ← solo-classic.json
 * - map_mshi8l3p_yhctj2 (1p) ← solo_spiral.json
 * - map_mshdzkhc_hbwgyg (2p) ← squareface1.json
 */
import { parseGameMap, type GameMap } from "../map.js";
import map_ranked_classic from "./ranked-classic.json" with { type: "json" };
import map_solo_classic from "./solo-classic.json" with { type: "json" };
import map_solo_spiral from "./solo_spiral.json" with { type: "json" };
import map_squareface1 from "./squareface1.json" with { type: "json" };

const MAPS: GameMap[] = [
  parseGameMap(map_ranked_classic),
  parseGameMap(map_solo_classic),
  parseGameMap(map_solo_spiral),
  parseGameMap(map_squareface1),
];

export const MAP_CATALOG: Readonly<Record<string, GameMap>> = Object.freeze(
  Object.fromEntries(MAPS.map((m) => [m.id, m])),
);
